# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='foto',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
